import classification from './classification';
export default [
  {
    id: 'title00',
    label: 'S/N',
    show: true,
    type: '',
    sample: '#1',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title01',
    label: 'Дата регистрации',
    show: true,
    type: '',
    sample: '10_июня_2014г',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title02',
    label: 'Название сервиса',
    show: true,
    type: '',
    sample: 'Gmail',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title03',
    label: 'Логин',
    show: true,
    type: '',
    sample: 'name@gmail.com',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title04',
    label: 'Пароль',
    show: true,
    type: '',
    sample: 'Passw%7!3rd',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title05',
    label: 'Дата установки пароля',
    show: true,
    type: '',
    sample: '31_01_2014',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title06',
    label: 'Имя пользователя',
    show: true,
    type: '',
    sample: 'Константин',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title07',
    label: 'Фамилия пользователя',
    show: true,
    type: '',
    sample: 'Циолковский',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title08',
    label: 'Дата рождения',
    show: true,
    type: '',
    sample: '29_02_1970',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title09',
    label: 'Пол',
    show: true,
    type: '',
    sample: 'мужск',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title10',
    label: 'Секретный вопрос',
    show: true,
    type: 'text',
    sample: 'В каком городе родился?',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title11',
    label: 'Секретный ответ',
    show: true,
    type: 'text',
    sample: 'В городе Бостон',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title12',
    label: 'Почта для связи',
    show: true,
    type: '',
    sample: 'name@anymail.com',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title13',
    label: 'Адрес',
    show: true,
    type: 'text',
    sample: 'Город Зеленоград',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title14',
    label: 'Доп поле',
    show: true,
    type: 'text',
    sample: 'Что-нибудь',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title15',
    label: 'конт. телеф.',
    show: true,
    type: '',
    sample: '+7-900-800-70-60',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title16',
    label: 'кредитная карта',
    show: true,
    type: '',
    sample: 'виза 0102 0304 0506 8888',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title17',
    label: 'Ключевые слова',
    show: true,
    type: 'text',
    sample: 'Почта, работа, гугл, официал.',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title18',
    label: 'Веб адрес сервиса',
    show: true,
    type: '',
    sample: 'https://www.google.com/gmail/about/',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title19',
    label: 'Бонус1',
    show: true,
    type: 'text',
    sample: 'для бонус1',
    align: 'left',
    titlenote: 'New Note',
  },
{
    id: 'title20',
    label: 'Бонус2',
    show: true,
    type: 'text',
    sample: 'для бонус2',
    align: 'left',
    titlenote: 'New Note',
  },

  {
    id: 'title21',
    label: 'STARS',
    type: 'rating',
    show: true,
    sample: 5,
    align: 'left',
    titlenote: 'New Note',
  },
  {
    id: 'year',
    label: 'Year',
    type: 'year',
    show: false,
    sample: 2015,
    titlenote: 'New Note',
  },
  {
    id: 'rating',
    label: 'Rating',
    type: 'rating',
    show: false,
    sample: 5,
    titlenote: 'New Note',
  },
  {
    id: 'comments',
    label: 'Comments',
    type: 'text',
    sample: 'Nice for the price',
    show: false,
    titlenote: 'New Note',
  },
]

