import classification from './classification';
export default [
[{
    id: 'title00',
    label: 'Заметка №',
    show: true,
    type: '',
    sample: '№1',
    align: 'left',
    titlenote: 'SimpleNote-New',
  },
{
    id: 'title01',
    label: 'Заметка',
    show: true,
    type: 'textarea',
    sample: 'Любой текст',
    align: 'left',
    titlenote: 'SimpleNote-New',
  },
],

[{
    id: 'title00',
    label: 'S/N',
    show: true,
    type: '',
    sample: '#01',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title01',
    label: 'Срок действия',
    show: true,
    type: '',
    sample: '07 2014г',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title02',
    label: 'Номер карты',
    show: true,
    type: '',
    sample: '6868 2534...',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title03',
    label: 'Тип карты',
    show: true,
    type: '',
    sample: 'Visa, Maestro...',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title04',
    label: 'Имя пользователя',
    show: true,
    type: '',
    sample: 'JAMES BOND',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title05',
    label: 'Код карты',
    show: true,
    type: '',
    sample: '567',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
{
    id: 'title06',
    label: 'Банк',
    show: true,
    type: '',
    sample: 'Сбербанк',
    align: 'left',
    titlenote: 'KartBankNote-New',
  },
],

[   {
        "id": "title00",
        "label": "Запись №",
        "show": true,
        "type": "input",
        "sample": "#1",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title01",
        "label": "Дата регистрации",
        "show": true,
        "type": "input",
        "sample": "10_июня_2011г",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title02",
        "label": "Название сервиса",
        "show": true,
        "type": "input",
        "sample": "Gmail",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title03",
        "label": "Логин",
        "show": true,
        "type": "input",
        "sample": "name@gmail.com",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title04",
        "label": "Пароль",
        "show": true,
        "type": "input",
        "sample": "Passw%7!3rd",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title05",
        "label": "Дата установки пароля",
        "show": true,
        "type": "input",
        "sample": "31_01_2014",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title06",
        "label": "Имя пользователя",
        "show": true,
        "type": "input",
        "sample": "Константин",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title07",
        "label": "Фамилия пользователя",
        "show": true,
        "type": "input",
        "sample": "Циолковский",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title08",
        "label": "Дата рождения",
        "show": true,
        "type": "input",
        "sample": "29_02_1970",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title09",
        "label": "Пол",
        "show": true,
        "type": "input",
        "sample": "мужск",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title10",
        "label": "Секретный вопрос",
        "show": true,
        "type": "textarea",
        "sample": "В каком городе родился?",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title11",
        "label": "Секретный ответ",
        "show": true,
        "type": "textarea",
        "sample": "В городе Бостон",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title12",
        "label": "Почта для связи",
        "show": true,
        "type": "input",
        "sample": "name@anymail.com",
        "align": "left",
        "titlenote": "List_accounts-New"
    },

    {
        "id": "title13",
        "label": "конт. телеф.",
        "show": true,
        "type": "input",
        "sample": "+7-900-800-70-60",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title14",
        "label": "кредитная карта",
        "show": true,
        "type": "input",
        "sample": "виза 0102 ... 8888",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title15",
        "label": "Ключевые слова",
        "show": true,
        "type": "textarea",
        "sample": "Почта, работа, гугл, официал.",
        "align": "left",
        "titlenote": "List_accounts-New"
    },
    {
        "id": "title16",
        "label": "Веб адрес сервиса",
        "show": true,
        "type": "input",
        "sample": "https://www.google.com/gmail/about/",
        "align": "left",
        "titlenote": "List_accounts-New"
    },

    {
        "id": "year",
        "label": "Year",
        "type": "year",
        "show": false,
        "sample": 2015,
        "titlenote": "List_accounts-New"
    },
    {
        "id": "rating",
        "label": "Rating",
        "type": "rating",
        "show": false,
        "sample": 5,
        "titlenote": "List_accounts-New"
    },
],
[{
    id: 'title00',
    label: 'ISBN:',
    show: true,
    type: 'input',
    sample: '№1',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
{
    id: 'title01',
    label: 'Название:',
    show: true,
    type: 'input',
    sample: 'Любой текст',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title02',
    label: 'Автор:',
    show: true,
    type: 'input',
    sample: 'Любой текст',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title03',
    label: 'Художник:',
    show: true,
    type: 'input',
    sample: 'Любой текст',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title04',
    label: 'Год издания:',
    show: true,
    type: 'year',
    sample: '2014',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title05',
    label: 'Кол.Страниц:',
    show: true,
    type: 'input',
    sample: '208',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title06',
    label: 'Размер мм:',
    show: true,
    type: 'input',
    sample: '220 x 170 x 20',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title07',
    label: 'Обложка',
    show: true,
    type: 'input',
    sample: 'Твердая. Мягкая.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title08',
    label: 'Илюстрации:',
    show: true,
    type: 'input',
    sample: 'цветные, черно-белые',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title09',
    label: 'Цена, руб:',
    show: true,
    type: 'input',
    sample: 'Любой текст',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title10',
    label: 'Издательство:',
    show: true,
    type: 'input',
    sample: 'Речь',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title11',
    label: 'Серия:',
    show: true,
    type: 'input',
    sample: 'Золотое наследие',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title12',
    label: 'Категория:',
    show: true,
    type: 'input',
    sample: '6+',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title13',
    label: 'Состояние:',
    show: true,
    type: 'input',
    sample: 'Новое. хорошее.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title14',
    label: 'Миниатюра:',
    show: true,
    type: 'textarea',
    sample: 'изображение',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title15',
    label: 'Тип печати:',
    show: true,
    type: 'input',
    sample: 'офсет. мелованная. газетная.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title16',
    label: 'Курс $:',
    show: true,
    type: 'input',
    sample: '62.4 rub',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title17',
    label: 'Теги:',
    show: true,
    type: 'textarea',
    sample: 'детская. фантастика.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title18',
    label: 'Дубликат:',
    show: true,
    type: 'input',
    sample: 'нету.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title19',
    label: 'Статус:',
    show: true,
    type: 'input',
    sample: 'обязательно. желательно.',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title20',
    label: 'DateRecord:',
    show: false,
    type: 'input',
    sample: 'дата записи',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
  {
    id: 'title21',
    label: 'IdRecord:',
    show: false,
    type: 'input',
    sample: 'Id записи',
    align: 'left',
    titlenote: 'BiblioLib-New',
  },
],
]

